### test connection
GET http://localhost:5029/

### get news connection
GET http://localhost:5029/get


### create a news
POST http://localhost:5029/create
Content-Type: application/json

{
  "text": "new text from api.http file"
}
